### ISSUE TITLE
stw:Bodenseeraum - wd:

### ISSUE THREAD

**Issue by jneubert** [zbw/stw-mappings#1]
Das für [stw:Bodenseeraum](http://zbw.eu/stw/descriptor/30083-1) am besten treffende Item ist [wd:Bodenseeraum](https://www.wikidata.org/wiki/Q34947397). Alle WP-Seiten und externe Links hängen jedoch an [wd:Bodensee](https://www.wikidata.org/wiki/Q4127). 

Vorschlag: Zusätzlicher narrowMatch zu wd:Bodensee.

**Comment by mfaden** [comment]
Schon über Ausnahmeliste erledigt!
