### ISSUE TITLE
10641-5 Komparativer Vorteil = Q215551 Komparativer Kostenvorteil 

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1026]
10641-5 Komparativer Vorteil > Q1426665  Ricardo-Modell
10641-5,>,Q1426665,#,Mehrfachmatch

10641-5 Komparativer Vorteil ^ Q1430930 Revealed Comparative Advantage
10641-5,^,Q1430930,#,Mehrfachmatch

**Comment by AndreasOskar** [comment]
Änderung der Relationen

10641-5 Komparativer Vorteil > Q1426665 Ricardo-Modell
10641-5,>,Q1426665,#,Mehrfachmatch
