### ISSUE TITLE
19448-3  Standortmarketing = Q2090622 Standortmarketing

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1123]
19448-3  Standortmarketing = Q1787396  Standortmarketing
19448-3,=,Q1787396,#,Mehrfachmatch

19448-3  Standortmarketing > Q2138409 Regionalmarketing
19448-3,>,Q2138409,#,Mehrfachmatch

**Comment by AndreasOskar** [comment]
Den deutschen Begriff umgehängt nach Q2090622 und den zweiten UK (Q1787396) auf *
