### ISSUE TITLE
11278-0 Offene Stellen   =  Q72058347  offene Stellen 

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1169]
11278-0 Offene Stellen =  Q4102597  Jobangebot 
11278-0,=,Q4102597,#,Mehrfachmatch

**Comment by jneubert** [comment]
Wenn wir die Items so verstehen wollen, dass einmal konkrete Jobangebote gemeint sind und einmal die Statistikkategorie - sonst könnten die Items gemergt werden -, dann hätten wir doch zu letzterem ein exactMatch, und zu ersterem ein closeMatch? Oder übersehe ich was?

**Comment by AndreasOskar** [comment]
Folgendermaßen geändert:
11278-0 Offene Stellen * Q4102597 Jobangebot
11278-0,*,Q4102597,#,Mehrfachmatch
