### ISSUE TITLE
13985-0 Büroberufe = Q64275409 Büroarbeiter 

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1187]
13985-0 Büroberufe = Q51073243 Büroangestellter
13985-0,=,Q51073243,#,Mehrfachmatch

13985-0 Büroberufe > Q1021658 Bürokaufmann 
13985-0,>,Q1021658,#,Mehrfachmatch

13985-0 Büroberufe >  Q80687 Sekretär 
13985-0,>,Q80687,#,Mehrfachmatch

**Comment by jneubert** [comment]
Was spricht gegen einen Merge von Q51073243 und Q64275409? Ich sehe kein Ausschlusskriterium (unterschiedliche WP-Seiten oder Deskriptoren in anderen Thesauri). Was wir gewinnen, ist weniger mentaler Overhead bei STW-NutzerInnen und ein einheitliches Ziel für indirekte Mappings.

**Comment by AndreasOskar** [comment]
Nun Merge durchgeführt.
