### ISSUE TITLE
11036-3 Selbstverwalteter Betrieb =  Q47535966 Selbstverwalteter Betrieb

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1192]
11036-3 Selbstverwalteter Betrieb ^ Q15981562 Arbeiterselbstverwaltung
11036-3,^,Q15981562,#,Mehrfachmatch

11036-3 Selbstverwalteter Betrieb =  Q1939471 Mitarbeiterunternehmen
11036-3,=,Q1939471,#,Mehrfachmatch

**Comment by AndreasOskar** [comment]
Mapping sollte folgendermaßen aussehen:
Hauptrelation:
11036-3 Selbstverwalteter Betrieb = Q1939471 Mitarbeiterunternehmen

Nebenrelationen:
11036-3 Selbstverwalteter Betrieb ^ Q15981562 Arbeiterselbstverwaltung
11036-3,^,Q15981562,#,Mehrfachmatch

11036-3 Selbstverwalteter Betrieb * Q47535966 Selbstverwalteter Betrieb
11036-3,*,Q47535966,#,Mehrfachmatch
