### ISSUE TITLE
11969-1  Informelle Siedlung = Q201759 Slum

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#1202]
11969-1  Informelle Siedlung * Q1294703 Informelle Siedlung
11969-1,*,Q1294703,#,Mehrfachmatch

11969-1  Informelle Siedlung = Q693827 Favela 
11969-1,=,Q693827,#,Mehrfachmatch

**Comment by AndreasOskar** [comment]
Mapping sollte folgendermaßen aussehen:

Hauptrelation:
11969-1 Informelle Siedlung = Q1294703 Informelle Siedlung

Nebenrelationen:
11969-1 Informelle Siedlung > Q201759 Slum
11969-1,>,Q201759,#,Mehrfachmatch

11969-1 Informelle Siedlung > Q693827 Favela
11969-1,>,Q693827,#,Mehrfachmatch
