### ISSUE TITLE
13671-2 Bürotechnik = Bürotechnik (Q106707749) 

### ISSUE THREAD

**Issue by mfaden** [zbw/stw-mappings#143]
Taschenrechner  Taschenrechner (Q31087) 
Schreibmaschine  Schreibmaschine (Q46335) 
Büromaschine/Office machinery  Büromaschine (Q1021672) 
Bürokommunikation = in WD über aka auf Bürotechnik umgeleitet.
Office communication system  = in WD über aka auf Bürotechnik umgeleitet.

Nicht verknüpft: Bf. Bildschirmarbeit/Computerarbeitsplatz Bildschirmarbeitsplatz (Q363931) 
Issue offen halten...

**Comment by mfaden** [comment]
In Redaktionsliste überführt, wird dort bearbeitet!

**Comment by AndreasOskar** [comment]
ND Bildschirmarbeit wurde stillgelet.
