### ISSUE TITLE
14335-6 Automat = Selbstbedienungsautomat (Q211584) 

### ISSUE THREAD

**Issue by mfaden** [zbw/stw-mappings#151]
Automat ?
Gaming machine n.v.
Leistungsautomat n.v.
Musikautomat WD andere Definition (selbstspielendes Musikinstrument)

Münzautomat/Warenautomat 
Slot machine/Spielautomat  Einarmiger Bandit (Q33972) 
Unterhaltungsautomat n.v.

Angegebene verknüpft, offen lassen bis zur Klärung!

**Comment by mfaden** [comment]
Offen lassen! Automat muss von der Redaktion geklärt werden...

**Comment by AndreasOskar** [comment]
Automat wurde mittlerweile aufgesplittet.
Neue Mapping-Relationen gehen erst nach Erstellung eines Aktualisierungsworkflows
