### ISSUE TITLE
stw:Fischerei wd:

### ISSUE THREAD

**Issue by jneubert** [zbw/stw-mappings#17]
Drei überlappende Items:
- https://www.wikidata.org/wiki/Q14373 Tätigkeit des Fischens, aber de:Wirtschaftszweig
- https://www.wikidata.org/wiki/Q180538 Wirtschaftszweig, aber ohne de-Pagelink
- https://www.wikidata.org/wiki/Q11202642 wirtschaftliche Aktivität und Wirtschaftszweig

**Comment by mfaden** [comment]
Link zum ältesten Item (Q14373) hergestellt. Die Entscheidung zu Gunsten dieses Links fiel vor allem wegen der deutschen Übersetzung. Bitte den Rest in die Ausnahmeliste eintragen.

**Comment by mfaden** [comment]
Q11202642 von deutsch nur "Fischerei" in "Kommezielle Fischerei" umgetauft.

**Comment by jneubert** [comment]
de:Fischerei nach wd: verschoben

**Comment by mfaden** [comment]
Erledigt!
