### ISSUE TITLE
stw:Gastronomie - wd:

### ISSUE THREAD

**Issue by mfaden** [zbw/stw-mappings#35]
https://www.wikidata.org/wiki/Q171141
https://www.wikidata.org/wiki/Q29584322

Property-Konflikt. Kann man da etwas tun? Ist wieder der Belgier...

**Comment by mfaden** [comment]
Mit Joachim besprechen?

**Comment by mfaden** [comment]
"Fehler während „Zusammenlegen mit: Q171141“: The two items cannot be merged because one of them links to the other using the properties: P460, P460

If you believe it's an error, please report it here with source and destination of merge."

**Comment by jneubert** [comment]
merged (after deleting P460)
