### ISSUE TITLE
stw:Gebäudemanagement wd:??

### ISSUE THREAD

**Issue by jneubert** [zbw/stw-mappings#54]
http://zbw.eu/stw/descriptor/18746-0 ist mit 

https://www.wikidata.org/wiki/Q1323766 verknüpft - sollte aber 

eher https://www.wikidata.org/wiki/Q837060

sein (wd mergen?).

**Comment by mfaden** [comment]
Ist leider nicht zu mergen, da zwei japanische WP-Einträge.
Umgehängt und erledigt!
