### ISSUE TITLE
11191-5 Kündigung = Q17052147 dismissal

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#564]
11191-5 Kündigung = Q1797063 Kündigung (allgemeiner)
11191-5,=,Q1797063,#,Mehrfachmatch

11191-5 Kündigung > Q1685500 betriebsbedingte Kündigung
11191-5,>,Q1685500,#,Mehrfachmatch

11191-5 Kündigung =  Q20664756 Personalfreisetzung
11191-5,=,Q20664756,#,Mehrfachmatch

**Comment by agrueta** [comment]
change because of team decision (07.11.22)

11191-5 Kündigung = Q17353762 Kündigung (dt. Arbeitsrecht)
11191-5,=,Q17353762,#564,Mehrfachmatch

11191-5 Kündigung > Q16216484 Kündigung (Rechtsbegriff)
11191-5,>,Q16216484,#564,Mehrfachmatch

11191-5 Kündigung = Q1797063 Kündigung (allgemeiner)
11191-5,=,Q1797063,#,Mehrfachmatch

11191-5 Kündigung > Q1685500 betriebsbedingte Kündigung
11191-5,>,Q1685500,#,Mehrfachmatch

**Comment by AndreasOskar** [comment]
Folgende Änderung durchgeführt - im Sinne von Instanz:
11191-5 Kündigung < Q17353762 Kündigung (dt. Arbeitsrecht)
11191-5,=,Q17353762,https://github.com/zbw/stw-mappings/issues/564,Mehrfachmatch
