### ISSUE TITLE
 Mais (Q25618328) / Mais (Q11575) /14093-4 Maize

### ISSUE THREAD

**Issue by mfaden** [zbw/stw-mappings#66]
Die beiden Qs haben jeweils eine Verlinkung zu Swahili (sw), aber zu zwei verschiedenen Items, die sich nur durch einen Buchstaben Muhindi/Mahindi unterscheiden und deshalb von uns nicht zusammengelegt werden können.

**Comment by mfaden** [comment]
Über Ausnahmeliste geregelt...

**Comment by AndreasOskar** [comment]
"dag" (Sprache) umgehängt und "mahindi" (Bezeichnung) auf * gesetzt….
