### ISSUE TITLE
12497-4 Kostenartenrechnung = Q106560108 Kostenartenrechnung

### ISSUE THREAD

**Issue by agrueta** [zbw/stw-mappings#665]
12497-4 Kostenartenrechnung ~ Q1275689 Kostenart
12497-4,~,Q1275689,#,Mehrfachmatch

**Comment by mfaden** [comment]
Email von Joachim vom 14.01.22,, dass in der Ausnahmeliste ~ durch * ersetzt wurde. Hier korrigiert durch mf am 15.12.22
